// Fetches a business website and scores it against the 12 checks automatically.
// This is the part that used to take you ten minutes per lead.

const CHECKS = require('./checks');
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';
const BROWSER_HEADERS = {
  'user-agent': UA,
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
  'accept-language': 'en-US,en;q=0.9',
  'upgrade-insecure-requests': '1',
};

// Statuses that mean "we were not allowed to look", not "their site is broken".
// Never pitch off one of these: the owner will open the site on his phone,
// see it working, and the call is over.
const BLOCKED_STATUS = new Set([401, 403, 405, 406, 418, 429, 503]);

function connectionReason(code) {
  if (/ENOTFOUND|EAI_AGAIN/.test(code)) return { reason: 'domain does not resolve', proven: true };
  if (/ECONNREFUSED/.test(code)) return { reason: 'server refuses connections', proven: true };
  if (/CERT_HAS_EXPIRED/.test(code)) return { reason: 'expired SSL certificate', proven: true };
  if (/DEPTH_ZERO_SELF_SIGNED_CERT|SELF_SIGNED|ERR_TLS|ALT_NAME/.test(code)) return { reason: 'broken SSL certificate', proven: true };
  if (/timeout|ETIMEDOUT|UND_ERR_CONNECT_TIMEOUT/i.test(code)) return { reason: 'timed out — too slow to load', proven: true };
  return { reason: `could not connect (${code})`, proven: false };
}

const BUILDERS = [
  [/wix\.com|_wixCssImports|X-Wix-/i, 'Wix'],
  [/squarespace|static1\.squarespace/i, 'Squarespace'],
  [/godaddy|starfieldtech|websitebuilder/i, 'GoDaddy builder'],
  [/weebly|editmysite/i, 'Weebly'],
  [/wp-content|wp-includes/i, 'WordPress'],
  [/shopify|cdn\.shopify/i, 'Shopify'],
  [/webs\.com|homestead|networksolutions|yellowpages\.com\/website/i, 'legacy builder'],
];

// Unambiguous: only a parked or expired domain says these.
const PARKED_STRONG = /this domain (is|may be) for sale|buy this domain|parked (free )?courtesy|godaddy\.com\/domainsearch|sedoparking|hugedomains|domain( name)? (has )?expired|this site is temporarily unavailable/i;

// Ambiguous: a real shop says "coming soon" about a product and "under
// construction" about a remodel. Only treat it as a placeholder when it is the
// headline of a page that has nowhere to go.
const PARKED_WEAK = /coming soon|under construction|site temporarily unavailable|website (is )?(under|being) (built|developed)/i;

// The hosting control panel's own placeholder. The domain resolves, the server
// answers, and there is no site: the strongest lead there is, and one that
// looks like a working site to every check unless you name it.
const SERVER_DEFAULT = /web server'?s default page|there is no web site at this address|plesk international|generated by plesk|welcome to nginx|apache2? (ubuntu |debian |centos )?default page|it works!|iis windows server|future home of something quite cool|test page for the (apache|nginx) http server|cpanel(®)? default|index of \//i;

function looksParked(html, bytes, hasPhone) {
  if (PARKED_STRONG.test(html)) return true;

  const title = (html.match(/<title[^>]*>([\s\S]*?)<\/title>/i) || [])[1] || '';
  const headings = (html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/gi) || []).join(' ');
  const links = (html.match(/<a\s[^>]*href=/gi) || []).length;

  // A placeholder announces itself in the title or the one heading, and has
  // essentially nothing to click.
  if (PARKED_WEAK.test(title + ' ' + headings) && links < 5) return true;

  return bytes < 600 && !hasPhone;
}

async function grab(url, timeoutMs) {
  const ctl = new AbortController();
  const t = setTimeout(() => ctl.abort(), timeoutMs);
  const started = Date.now();
  try {
    const res = await fetch(url, { redirect: 'follow', signal: ctl.signal, headers: BROWSER_HEADERS });
    const html = await res.text();
    return { ok: true, status: res.status, finalUrl: res.url, html, ms: Date.now() - started, bytes: html.length };
  } catch (e) {
    const code = e.name === 'AbortError' ? 'timeout' : (e.cause?.code || e.message);
    return { ok: false, code, error: String(code), ms: Date.now() - started };
  } finally { clearTimeout(t); }
}

// Pull whatever the site already publishes about itself, so business.json
// arrives half-filled instead of empty.
function extract(html) {
  const out = {};
  const title = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  if (title) out.title = title[1].replace(/\s+/g, ' ').trim();
  const desc = html.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)/i);
  if (desc) out.description = desc[1].trim();

  const tel = html.match(/href=["']tel:([^"']+)/i);
  const loose = html.match(/\(?\b([2-9]\d{2})\)?[-.\s]?(\d{3})[-.\s]?(\d{4})\b/);
  if (tel) out.phone = tel[1].trim();
  else if (loose) out.phone = `(${loose[1]}) ${loose[2]}-${loose[3]}`;

  const zip = html.match(/\b([A-Z][a-z]+(?:\s[A-Z][a-z]+)*),?\s+(CA|California)\s+(9\d{4})\b/);
  if (zip) out.cityState = { city: zip[1], state: 'CA', zip: zip[3] };

  const street = html.match(/\b(\d{1,6}\s+(?:[NSEW]\.?\s+)?[A-Z][A-Za-z.'-]*(?:\s+[A-Z][A-Za-z.'-]*){0,2}\s+(?:St|Street|Ave|Avenue|Blvd|Boulevard|Rd|Road|Dr|Drive|Way|Ln|Lane|Ct|Court|Pl|Place|Pkwy|Parkway|Hwy|Highway))\.?\b/);
  if (street) out.street = street[1].replace(/\s+/g, ' ').trim();

  const years = [...html.matchAll(/(?:©|&copy;|copyright)[^0-9]{0,20}((?:19|20)\d{2})/gi)].map((m) => +m[1]);
  if (years.length) out.copyrightYear = Math.max(...years);

  for (const [re, name] of BUILDERS) if (re.test(html)) { out.builder = name; break; }

  // If they already ship LocalBusiness JSON-LD, take the good data straight out.
  for (const m of html.matchAll(/<script[^>]+application\/ld\+json[^>]*>([\s\S]*?)<\/script>/gi)) {
    try {
      const nodes = [].concat(JSON.parse(m[1].trim()));
      for (const n of nodes.flatMap((x) => x['@graph'] || [x])) {
        if (!/business|store|restaurant|service|organization|shop/i.test(n['@type'] || '')) continue;
        out.ldName = out.ldName || n.name;
        out.ldPhone = out.ldPhone || n.telephone;
        if (n.address?.streetAddress) out.ldAddress = {
          street: n.address.streetAddress, city: n.address.addressLocality,
          state: n.address.addressRegion, zip: n.address.postalCode,
        };
        if (n.aggregateRating) out.ldRating = { value: n.aggregateRating.ratingValue, count: n.aggregateRating.reviewCount };
      }
    } catch { /* malformed JSON-LD is itself a finding, not a crash */ }
  }
  return out;
}

function score(html, page, httpsWorked) {
  const h = html;
  const has = (re) => re.test(h);
  return {
    https:    httpsWorked,
    mobile:   has(/<meta[^>]+name=["']viewport["'][^>]+width\s*=\s*device-width/i),
    speed:    page.ms < 2500 && page.bytes < 1_500_000,
    phoneTap: has(/href=["']tel:/i),
    hours:    has(/\b(mon|tues?|wed|thur?s?|fri|sat|sun)[a-z]*\.?\s*[-–—:]/i) || has(/\bhours\b[\s\S]{0,120}\d{1,2}\s*(:\d{2})?\s*(am|pm)/i),
    address:  has(/\b\d{1,6}\s+[A-Z][A-Za-z.]*\s+(st|street|ave|avenue|blvd|boulevard|rd|road|dr|drive|way|ln|lane|ct|pl|pkwy|hwy)\b/i) && has(/\b9\d{4}\b/),
    services: has(/\$\s?\d/) ,
    reviews:  has(/testimonial|review/i) && has(/★|⭐|stars?\b|yelp|google review/i),
    cta:      has(/href=["']tel:/i) || has(/\b(call (us )?now|book (online|now|an? appointment)|schedule (a |your )?(service|appointment)|free (estimate|quote|consultation)|request a quote)\b/i),
    seo:      has(/application\/ld\+json/i),
    meta:     has(/<title[^>]*>\s*\S[\s\S]{4,}?<\/title>/i)
              && !has(/<title[^>]*>\s*(untitled document|home|welcome|index|new page \d*|my site|website)\s*<\/title>/i)
              && has(/<meta[^>]+name=["']description["'][^>]+content=["']\s*\S/i),
    social:   has(/property=["']og:(title|image|description)["']/i),
  };
}

// A dead or missing site is the strongest lead there is, so it scores as a
// full miss on everything rather than being dropped from the list.
const allFalse = () => Object.fromEntries(CHECKS.map((c) => [c.key, false]));

async function audit(rawUrl, { timeout = 12000 } = {}) {
  if (!rawUrl) {
    return { url: null, reachable: false, verified: false, reason: 'no website',
             checks: allFalse(), gaps: CHECKS.length, info: {} };
  }

  const bare = String(rawUrl).replace(/^https?:\/\//i, '').replace(/\/+$/, '');
  const root = bare.split('/')[0];

  // Try HTTPS, then plain HTTP. A site that only answers on HTTP is a real
  // finding; one that answers on neither needs explaining before we call it dead.
  let page = await grab('https://' + bare, timeout);
  let httpsWorked = page.ok && page.status < 400;

  if (!httpsWorked) {
    const insecure = await grab('http://' + bare, timeout);
    if (insecure.ok && insecure.status < 400) page = insecure;
    else if (!page.ok && insecure.ok) page = insecure;
  }

  // The listed URL is often a deep link that has rotted while the site itself
  // is fine. Check the root before accusing anyone of a dead website.
  if (page.ok && page.status === 404 && bare !== root) {
    for (const scheme of ['https://', 'http://']) {
      const home = await grab(scheme + root, timeout);
      if (home.ok && home.status < 400) { page = home; httpsWorked = scheme === 'https://'; break; }
    }
  }

  if (page.ok && BLOCKED_STATUS.has(page.status)) {
    // Cloudflare and friends. We learned nothing about their site, so this is
    // not a lead — and a site behind a WAF usually has someone maintaining it.
    return { url: bare, reachable: null, verified: false, blocked: true,
             reason: `blocked our check (HTTP ${page.status})`,
             checks: allFalse(), gaps: 0, info: {} };
  }

  if (!page.ok) {
    const { reason, proven } = connectionReason(page.code);
    return { url: bare, reachable: false, verified: proven, blocked: !proven,
             reason, checks: allFalse(), gaps: proven ? CHECKS.length : 0, info: {} };
  }

  if (page.status >= 400) {
    return { url: bare, reachable: false, verified: true,
             reason: `returns HTTP ${page.status}`, ms: page.ms,
             checks: allFalse(), gaps: CHECKS.length, info: {} };
  }

  if (SERVER_DEFAULT.test(page.html)) {
    return { url: bare, finalUrl: page.finalUrl, reachable: true, verified: true,
             reason: 'no website — hosting default page', ms: page.ms, kb: Math.round(page.bytes / 1024),
             checks: allFalse(), gaps: CHECKS.length, info: {}, serverDefault: true };
  }

  const info = extract(page.html);
  const stats = { ms: page.ms, kb: Math.round(page.bytes / 1024) };

  if (looksParked(page.html, page.bytes, !!info.phone)) {
    return { url: bare, finalUrl: page.finalUrl, reachable: true, verified: true,
             reason: 'parked or placeholder page', ...stats,
             checks: allFalse(), gaps: CHECKS.length, info };
  }

  const checks = score(page.html, page, httpsWorked);
  const gaps = CHECKS.filter((c) => !checks[c.key]).length;
  const stale = info.copyrightYear && info.copyrightYear < new Date().getFullYear() - 2;

  return {
    url: bare, finalUrl: page.finalUrl, reachable: true, verified: true, ...stats,
    checks, gaps, info, stale,
    reason: [stale && `© ${info.copyrightYear}`, info.builder].filter(Boolean).join(', ') || null,
  };
}

module.exports = { audit, CHECKS };
