// Audits the RENDERED page, not the raw HTML.
//
// The raw-HTML audit reported missing hours, untappable numbers and no mobile
// layout on sites that plainly had all three — because those sites build their
// pages with JavaScript, and a regex over the served HTML sees an empty shell.
// Claiming a problem a business owner can disprove in five seconds is worse
// than finding nothing, so every content check now runs against the real DOM
// in a real browser at a real phone size.

const { chromium } = require('playwright-core');
const CHECKS = require('./checks');

const EXEC = process.env.CHROMIUM_PATH || undefined;
const PHONE = { width: 390, height: 844, isMobile: true, hasTouch: true, deviceScaleFactor: 2 };
const UA = 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 ' +
           '(KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1';

const BLOCKED = new Set([401, 403, 405, 406, 418, 429, 503]);

// Someone is already being paid to look after these. Royal Flowers is a
// BloomNation store with 159 reviews and a full price list on the page — it was
// never a lead, and pitching it would have been embarrassing.
const MANAGED = [
  [/bloomnation/i, 'BloomNation'], [/shopify|cdn\.shopify/i, 'Shopify'],
  [/squarespace|static1\.squarespace/i, 'Squarespace'], [/wix\.com|_wixCssImports|wixstatic/i, 'Wix'],
  [/webflow/i, 'Webflow'], [/duda(one)?|dudamobile/i, 'Duda'], [/godaddy.*websites|w\.sitey/i, 'GoDaddy Websites'],
  [/squareup|square-web|weebly/i, 'Square/Weebly'], [/bigcommerce/i, 'BigCommerce'],
  [/hubspot|hs-sites/i, 'HubSpot'], [/townsquareinteractive|dexyp|yext/i, 'a marketing agency'],
];

// The hosting panel's own placeholder. Catch it before reading anything off the
// page, or the hosting company's copyright gets reported as the business's.
const SERVER_DEFAULT = /web server'?s default page|there is no web site at this address|plesk international|generated by plesk|welcome to nginx|apache2? (ubuntu |debian |centos )?default page|it works!|iis windows server|future home of something quite cool|cpanel(®)? default/i;
const PARKED_STRONG = /this domain (is|may be) for sale|buy this domain|parked (free )?courtesy|godaddy\.com\/domainsearch|sedoparking|hugedomains|domain( name)? (has )?expired/i;
const PARKED_WEAK = /coming soon|under construction|website (is )?(under|being) (built|developed)/i;

// Runs inside the page, against what a visitor actually sees.
function probe() {
  const t = document.body ? document.body.innerText : '';
  const html = document.documentElement.outerHTML;
  const q = (s) => document.querySelector(s);
  const vp = q('meta[name="viewport"]');

  const telLinks = document.querySelectorAll('a[href^="tel:"]').length;
  const mapLinks = document.querySelectorAll('a[href*="maps.google"], a[href*="google.com/maps"], a[href*="maps.app.goo.gl"]').length;

  const dayRe = /\b(mon|tue|wed|thu|fri|sat|sun)[a-z]*\b/i;
  const timeRe = /\b(\d{1,2})(:\d{2})?\s*(am|pm)\b/i;
  const hoursText = /\bhours?\b|\bopen\b|\bclosed\b/i;

  return {
    text: t.slice(0, 20000),
    // A page that fits the phone: viewport meta AND nothing spilling sideways.
    viewportMeta: Boolean(vp && /width\s*=\s*device-width/i.test(vp.content || '')),
    overflows: document.documentElement.scrollWidth > window.innerWidth + 2,
    telLinks,
    mapLinks,
    hasHours: (dayRe.test(t) && timeRe.test(t)) || (hoursText.test(t) && timeRe.test(t)),
    hasAddress: /\b\d{1,6}\s+[A-Za-z][\w.'-]*(\s+[A-Za-z][\w.'-]*){0,3}\s+(st|street|ave|avenue|blvd|boulevard|rd|road|dr|drive|way|ln|lane|ct|court|pl|place|pkwy|parkway|hwy|highway)\b/i.test(t)
                && /\b9\d{4}\b/.test(t),
    hasPrices: /\$\s?\d/.test(t),
    hasReviews: /(review|testimonial)/i.test(t) && /(★|⭐|\bstars?\b|yelp|google)/i.test(t),
    hasCta: telLinks > 0 || /\b(call (us )?now|book (online|now|an? appointment)|schedule|request (a )?(quote|appointment)|free (estimate|quote|consultation)|contact us)\b/i.test(t),
    jsonLd: document.querySelectorAll('script[type="application/ld+json"]').length,
    title: (document.title || '').trim(),
    description: (q('meta[name="description"]') || {}).content || '',
    og: document.querySelectorAll('meta[property^="og:"]').length,
    bytes: html.length,
    textLen: t.length,
    copyright: (t.match(/(?:©|copyright)[^0-9]{0,20}((?:19|20)\d{2})/i) || [])[1] || null,
  };
}

async function auditRendered(rawUrl, { timeout = 25000, browser } = {}) {
  const bare = String(rawUrl).replace(/^https?:\/\//i, '').replace(/\/+$/, '');
  const own = !browser;
  const b = browser || await chromium.launch({ executablePath: EXEC, args: ['--no-sandbox'] });
  const ctx = await b.newContext({ ...PHONE, userAgent: UA, ignoreHTTPSErrors: false });
  let page = await ctx.newPage();

  const fail = (reason, verified) => ({
    url: bare, reachable: false, verified, blocked: !verified, reason,
    checks: Object.fromEntries(CHECKS.map((c) => [c.key, false])),
    gaps: verified ? CHECKS.length : 0, info: {},
  });

  try {
    let res = null, https = true;
    const started = Date.now();
    const isFile = /^file:\/\//i.test(String(rawUrl));
    try {
      if (isFile) {
        // Our own built pages are audited from disk. They will be served over
        // HTTPS once live, so that check is not held against them here.
        res = await page.goto(String(rawUrl), { waitUntil: 'domcontentloaded', timeout });
      } else {
        res = await page.goto('https://' + bare, { waitUntil: 'domcontentloaded', timeout });
      }
    } catch (e) {
      if (isFile) { await ctx.close(); if (own) await b.close(); return fail('could not open the file', false); }
      https = false;
      // A failed navigation leaves the page on chrome-error://, which interrupts
      // the very next goto. Retry plain HTTP on a clean page instead.
      await page.close().catch(() => {});
      page = await ctx.newPage();
      try { res = await page.goto('http://' + bare, { waitUntil: 'domcontentloaded', timeout }); }
      catch (e2) {
        await ctx.close(); if (own) await b.close();
        return fail(/ENOTFOUND|NAME_NOT_RESOLVED/i.test(e2.message) ? 'domain does not resolve'
          : /timeout/i.test(e2.message) ? 'timed out — too slow to load'
          : /CERT|SSL/i.test(e2.message) ? 'broken SSL certificate'
          : 'could not connect', /ENOTFOUND|NAME_NOT_RESOLVED|timeout|CERT|SSL/i.test(e2.message));
      }
    }
    const status = res ? res.status() : 0;
    if (BLOCKED.has(status)) {
      await ctx.close(); if (own) await b.close();
      return { ...fail(`blocked our check (HTTP ${status})`, false), reachable: null };
    }
    if (status >= 400) {
      await ctx.close(); if (own) await b.close();
      return fail(`returns HTTP ${status}`, true);
    }

    // Give the page a moment to actually build itself before judging it.
    await page.waitForLoadState('networkidle', { timeout: 8000 }).catch(() => {});
    // Walk the page the way a reader would, so lazy-loaded sections actually exist
    // before anything is judged missing.
    await page.evaluate(async () => {
      const step = Math.max(400, window.innerHeight * 0.8);
      for (let y = 0; y < document.body.scrollHeight && y < 30000; y += step) {
        window.scrollTo(0, y);
        await new Promise((r) => setTimeout(r, 120));
      }
      window.scrollTo(0, 0);
      await new Promise((r) => setTimeout(r, 250));
    }).catch(() => {});
    await page.waitForLoadState('networkidle', { timeout: 5000 }).catch(() => {});
    const ms = Date.now() - started;
    const p = await page.evaluate(probe);
    const finalUrl = page.url();
    const linkCount = await page.evaluate(() => document.querySelectorAll('a[href]').length);
    await ctx.close(); if (own) await b.close();

    const blank = Object.fromEntries(CHECKS.map((c) => [c.key, false]));
    if (SERVER_DEFAULT.test(p.text) || SERVER_DEFAULT.test(p.title)) {
      return { url: bare, finalUrl, reachable: true, verified: true, rendered: true, placeholder: true,
               serverDefault: true, ms, kb: Math.round(p.bytes / 1024),
               reason: 'no website — hosting default page', checks: blank, gaps: CHECKS.length, info: {} };
    }
    if (PARKED_STRONG.test(p.text) || (PARKED_WEAK.test(p.title) && linkCount < 5) || p.textLen < 120) {
      return { url: bare, finalUrl, reachable: true, verified: true, rendered: true, placeholder: true,
               ms, kb: Math.round(p.bytes / 1024),
               reason: 'parked or placeholder page', checks: blank, gaps: CHECKS.length, info: {} };
    }

    const platformHtml = await page.content().catch(() => '');
    const managed = MANAGED.find(([re]) => re.test(platformHtml));
    if (managed) {
      return { url: bare, finalUrl, reachable: true, verified: true, rendered: true,
               managed: managed[1], ms, kb: Math.round(p.bytes / 1024),
               reason: `built on ${managed[1]} — already maintained`,
               checks: Object.fromEntries(CHECKS.map((c) => [c.key, true])), gaps: 0, info: {} };
    }

    const defaultTitle = /^(untitled document|home|welcome|index|new page ?\d*|my site|website)$/i.test(p.title);
    const checks = {
      https,
      mobile:   p.viewportMeta && !p.overflows,
      speed:    ms < 6000,
      phoneTap: p.telLinks > 0,
      hours:    p.hasHours,
      address:  p.hasAddress || p.mapLinks > 0,
      services: p.hasPrices,
      reviews:  p.hasReviews,
      cta:      p.hasCta,
      seo:      p.jsonLd > 0,
      meta:     Boolean(p.title) && !defaultTitle && Boolean(p.description),
      social:   p.og > 0,
    };
    const gaps = CHECKS.filter((c) => !checks[c.key]).length;
    const stale = p.copyright && +p.copyright < new Date().getFullYear() - 2;

    return {
      url: bare, finalUrl, reachable: true, verified: true, rendered: true,
      ms, kb: Math.round(p.bytes / 1024), checks, gaps,
      info: { title: p.title, description: p.description, copyrightYear: p.copyright ? +p.copyright : null },
      stale,
      reason: stale ? `© ${p.copyright}` : null,
    };
  } catch (e) {
    await ctx.close().catch(() => {}); if (own) await b.close().catch(() => {});
    return fail('render failed: ' + e.message, false);
  }
}

module.exports = { auditRendered, chromium, EXEC };
