// Audits the RENDERED page, not the raw HTML.
//
// The raw-HTML audit reported missing hours, untappable numbers and no mobile
// layout on sites that plainly had all three — because those sites build their
// pages with JavaScript, and a regex over the served HTML sees an empty shell.
// Claiming a problem a business owner can disprove in five seconds is worse
// than finding nothing, so every content check now runs against the real DOM
// in a real browser at a real phone size.

const { chromium } = require('playwright-core');
const CHECKS = require('./checks');

// Find a browser without making anyone think about it. Playwright's bundled
// path changes with every version bump, and CI runners ship their own Chrome,
// so look in all the usual places rather than demanding an env var.
const EXEC = (() => {
  if (process.env.CHROMIUM_PATH) return process.env.CHROMIUM_PATH;
  const fs = require('fs'), path = require('path'), cp = require('child_process');
  const roots = [process.env.PLAYWRIGHT_BROWSERS_PATH, '/opt/pw-browsers',
                 path.join(require('os').homedir(), '.cache/ms-playwright')].filter(Boolean);
  for (const root of roots) {
    let dirs = [];
    try { dirs = fs.readdirSync(root).filter((d) => d.startsWith('chromium')); } catch { continue; }
    // newest build number first
    dirs.sort((a, b) => (+(b.match(/(\d+)$/) || [])[1] || 0) - (+(a.match(/(\d+)$/) || [])[1] || 0));
    for (const d of dirs) {
      for (const rel of ['chrome-linux/chrome', 'chrome-linux/headless_shell',
                         'chrome-mac/Chromium.app/Contents/MacOS/Chromium']) {
        const f = path.join(root, d, rel);
        if (fs.existsSync(f)) return f;
      }
    }
  }
  for (const bin of ['google-chrome', 'chromium', 'chromium-browser']) {
    try { return cp.execSync(`command -v ${bin}`, { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim() || undefined; }
    catch { /* not installed */ }
  }
  return undefined;   // let Playwright try its own default
})();
const PHONE = { width: 390, height: 844, isMobile: true, hasTouch: true, deviceScaleFactor: 2 };
const UA = 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 ' +
           '(KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1';

const BLOCKED = new Set([401, 403, 405, 406, 418, 429, 503]);

// Bot checks that answer 200 and render a page. Judging one of these means
// reporting a CAPTCHA's shortcomings back to a business owner.
const CHALLENGE = /\/\.well-known\/(sgcaptcha|captcha)|\/cdn-cgi\/(challenge|l\/chk_jschl)|__cf_chl|\/_Incapsula_|\/distil_r_captcha|\/challenge-platform/i;

// Someone is already being paid to look after these. Royal Flowers is a
// BloomNation store with 159 reviews and a full price list on the page — it was
// never a lead, and pitching it would have been embarrassing.
const MANAGED = [
  [/bloomnation/i, 'BloomNation'], [/shopify|cdn\.shopify/i, 'Shopify'],
  [/squarespace|static1\.squarespace/i, 'Squarespace'], [/wix\.com|_wixCssImports|wixstatic/i, 'Wix'],
  [/webflow/i, 'Webflow'], [/duda(one)?|dudamobile/i, 'Duda'], [/godaddy.*websites|w\.sitey/i, 'GoDaddy Websites'],
  [/squareup|square-web|weebly/i, 'Square/Weebly'], [/bigcommerce/i, 'BigCommerce'],
  [/hubspot|hs-sites/i, 'HubSpot'],
  // Booking platforms for salons, spas and clinics. These give a business a
  // photo gallery, a priced menu with durations and online booking — more than
  // a one-page rebuild offers. Revive Lash & Nail is on Bukkii and their page
  // is better than ours would be.
  [/bukkii/i, 'Bukkii'], [/vagaro/i, 'Vagaro'], [/booksy/i, 'Booksy'],
  [/glossgenius/i, 'GlossGenius'], [/squareup\.com\/appointments|square\.site/i, 'Square Appointments'],
  [/mindbodyonline|mindbody/i, 'Mindbody'], [/schedulicity/i, 'Schedulicity'],
  [/setmore|acuityscheduling|fresha/i, 'a booking platform'], [/townsquareinteractive|dexyp|yext/i, 'a marketing agency'],
];

// The hosting panel's own placeholder. Catch it before reading anything off the
// page, or the hosting company's copyright gets reported as the business's.
const SERVER_DEFAULT = /web server'?s default page|there is no web site at this address|plesk international|generated by plesk|welcome to nginx|apache2? (ubuntu |debian |centos )?default page|it works!|iis windows server|future home of something quite cool|cpanel(®)? default/i;
const PARKED_STRONG = /this domain (is|may be) for sale|buy this domain|parked (free )?courtesy|godaddy\.com\/domainsearch|sedoparking|hugedomains|domain( name)? (has )?expired/i;
const PARKED_WEAK = /coming soon|under construction|website (is )?(under|being) (built|developed)/i;

// Runs inside the page, against what a visitor actually sees.
function probe() {
  const t = document.body ? document.body.innerText : '';
  const html = document.documentElement.outerHTML;
  const q = (s) => document.querySelector(s);
  const vp = q('meta[name="viewport"]');

  const telLinks = document.querySelectorAll('a[href^="tel:"]').length;
  const mapLinks = document.querySelectorAll('a[href*="maps.google"], a[href*="google.com/maps"], a[href*="maps.app.goo.gl"]').length;

  const dayRe = /\b(mon|tue|wed|thu|fri|sat|sun)[a-z]*\b/i;
  const timeRe = /\b(\d{1,2})(:\d{2})?\s*(am|pm)\b/i;
  const hoursText = /\bhours?\b|\bopen\b|\bclosed\b/i;

  return {
    text: t.slice(0, 20000),
    // A page that fits the phone: viewport meta AND nothing spilling sideways.
    viewportMeta: Boolean(vp && /width\s*=\s*device-width/i.test(vp.content || '')),
    overflows: document.documentElement.scrollWidth > window.innerWidth + 2,
    telLinks,
    mapLinks,
    hasHours: (dayRe.test(t) && timeRe.test(t)) || (hoursText.test(t) && timeRe.test(t)),
    hasAddress: /\b\d{1,6}\s+[A-Za-z][\w.'-]*(\s+[A-Za-z][\w.'-]*){0,3}\s+(st|street|ave|avenue|blvd|boulevard|rd|road|dr|drive|way|ln|lane|ct|court|pl|place|pkwy|parkway|hwy|highway)\b/i.test(t)
                && /\b9\d{4}\b/.test(t),
    hasPrices: /\$\s?\d/.test(t),
    hasReviews: /(review|testimonial)/i.test(t) && /(★|⭐|\bstars?\b|yelp|google)/i.test(t),
    hasCta: telLinks > 0 || /\b(call (us )?now|book (online|now|an? appointment)|schedule|request (a )?(quote|appointment)|free (estimate|quote|consultation)|contact us)\b/i.test(t),
    jsonLd: document.querySelectorAll('script[type="application/ld+json"]').length,
    title: (document.title || '').trim(),
    description: (q('meta[name="description"]') || {}).content || '',
    og: document.querySelectorAll('meta[property^="og:"]').length,
    bytes: html.length,
    textLen: t.length,
    copyright: (t.match(/(?:©|copyright)[^0-9]{0,20}((?:19|20)\d{2})/i) || [])[1] || null,
  };
}

async function auditRendered(rawUrl, { timeout = 25000, browser, expectName } = {}) {
  const bare = String(rawUrl).replace(/^https?:\/\//i, '').replace(/\/+$/, '');
  const own = !browser;
  const b = browser || await chromium.launch({ executablePath: EXEC, args: ['--no-sandbox'] });
  const ctx = await b.newContext({ ...PHONE, userAgent: UA, ignoreHTTPSErrors: false });
  let page = await ctx.newPage();

  const fail = (reason, verified) => ({
    url: bare, reachable: false, verified, blocked: !verified, reason,
    checks: Object.fromEntries(CHECKS.map((c) => [c.key, false])),
    gaps: verified ? CHECKS.length : 0, info: {},
  });

  try {
    let res = null, https = true;
    const started = Date.now();
    const isFile = /^file:\/\//i.test(String(rawUrl));
    try {
      if (isFile) {
        // Our own built pages are audited from disk. They will be served over
        // HTTPS once live, so that check is not held against them here.
        res = await page.goto(String(rawUrl), { waitUntil: 'domcontentloaded', timeout });
      } else {
        res = await page.goto('https://' + bare, { waitUntil: 'domcontentloaded', timeout });
      }
    } catch (e) {
      if (isFile) { await ctx.close(); if (own) await b.close(); return fail('could not open the file', false); }
      https = false;
      // A failed navigation leaves the page on chrome-error://, which interrupts
      // the very next goto. Retry plain HTTP on a clean page instead.
      await page.close().catch(() => {});
      page = await ctx.newPage();
      try { res = await page.goto('http://' + bare, { waitUntil: 'domcontentloaded', timeout }); }
      catch (e2) {
        await ctx.close(); if (own) await b.close();
        return fail(/ENOTFOUND|NAME_NOT_RESOLVED/i.test(e2.message) ? 'domain does not resolve'
          : /timeout/i.test(e2.message) ? 'timed out — too slow to load'
          : /CERT|SSL/i.test(e2.message) ? 'broken SSL certificate'
          : 'could not connect', /ENOTFOUND|NAME_NOT_RESOLVED|timeout|CERT|SSL/i.test(e2.message));
      }
    }
    const status = res ? res.status() : 0;
    if (BLOCKED.has(status)) {
      await ctx.close(); if (own) await b.close();
      return { ...fail(`blocked our check (HTTP ${status})`, false), reachable: null };
    }
    if (status >= 400) {
      await ctx.close(); if (own) await b.close();
      return fail(`returns HTTP ${status}`, true);
    }

    // A bot challenge answers 200 and looks like a page, so nothing above
    // catches it — and then every finding describes a CAPTCHA rather than the
    // business. Their real site may be perfectly good; we simply never saw it.
    const challenged = page.url();
    if (CHALLENGE.test(challenged)) {
      await ctx.close(); if (own) await b.close();
      return { ...fail('bot check stood in front of the site, so we never saw it', false),
               reachable: null };
    }

    // Give the page a moment to actually build itself before judging it.
    await page.waitForLoadState('networkidle', { timeout: 8000 }).catch(() => {});
    // Walk the page the way a reader would, so lazy-loaded sections actually exist
    // before anything is judged missing.
    await page.evaluate(async () => {
      const step = Math.max(400, window.innerHeight * 0.8);
      for (let y = 0; y < document.body.scrollHeight && y < 30000; y += step) {
        window.scrollTo(0, y);
        await new Promise((r) => setTimeout(r, 120));
      }
      window.scrollTo(0, 0);
      await new Promise((r) => setTimeout(r, 250));
    }).catch(() => {});
    await page.waitForLoadState('networkidle', { timeout: 5000 }).catch(() => {});
    const ms = Date.now() - started;
    const p = await page.evaluate(probe);
    const finalUrl = page.url();
    const linkCount = await page.evaluate(() => document.querySelectorAll('a[href]').length);
    await ctx.close(); if (own) await b.close();

    const blank = Object.fromEntries(CHECKS.map((c) => [c.key, false]));
    if (SERVER_DEFAULT.test(p.text) || SERVER_DEFAULT.test(p.title)) {
      return { url: bare, finalUrl, reachable: true, verified: true, rendered: true, placeholder: true,
               serverDefault: true, ms, kb: Math.round(p.bytes / 1024),
               reason: 'no website — hosting default page', checks: blank, gaps: CHECKS.length, info: {} };
    }
    if (PARKED_STRONG.test(p.text) || (PARKED_WEAK.test(p.title) && linkCount < 5) || p.textLen < 120) {
      return { url: bare, finalUrl, reachable: true, verified: true, rendered: true, placeholder: true,
               ms, kb: Math.round(p.bytes / 1024),
               reason: 'parked or placeholder page', checks: blank, gaps: CHECKS.length, info: {} };
    }

    const platformHtml = await page.content().catch(() => '');

    // A credit line in the footer — "Design By Online Ethos", "Site by ..." —
    // means an agency is being paid to look after it. Korel Dentistry carried
    // one, along with hours listed twice, reviews, photos and a current
    // copyright. Walking into that is walking into a fight.
    const credit = (p.text.match(
      /\b(?:design(?:ed)?|site|website|web\s*design|developed|built|maintained)\s+by\s+([A-Z][\w&'.-]*(?:\s+[A-Z][\w&'.-]*){0,3})/i) || [])[1];
    const platformCredit = credit && /wordpress|shopify|wix|squarespace|weebly|godaddy|duda|webflow|bloomnation/i.test(credit);
    const agency = credit && !platformCredit ? credit.trim() : null;

    const managed = MANAGED.find(([re]) => re.test(platformHtml));
    if (agency) {
      return { url: bare, finalUrl, reachable: true, verified: true, rendered: true,
               managed: 'an agency — ' + agency, ms, kb: Math.round(p.bytes / 1024),
               reason: `credited to ${agency} — already maintained`,
               checks: Object.fromEntries(CHECKS.map((c) => [c.key, true])), gaps: 0, info: {} };
    }
    if (managed) {
      return { url: bare, finalUrl, reachable: true, verified: true, rendered: true,
               managed: managed[1], ms, kb: Math.round(p.bytes / 1024),
               reason: `built on ${managed[1]} — already maintained`,
               checks: Object.fromEntries(CHECKS.map((c) => [c.key, true])), gaps: 0, info: {} };
    }

    const defaultTitle = /^(untitled document|home|welcome|index|new page ?\d*|my site|website)$/i.test(p.title);
    const checks = {
      https,
      mobile:   p.viewportMeta && !p.overflows,
      speed:    ms < 6000,
      phoneTap: p.telLinks > 0,
      hours:    p.hasHours,
      address:  p.hasAddress || p.mapLinks > 0,
      services: p.hasPrices,
      reviews:  p.hasReviews,
      cta:      p.hasCta,
      seo:      p.jsonLd > 0,
      meta:     Boolean(p.title) && !defaultTitle && Boolean(p.description),
      social:   p.og > 0,
    };
    const gaps = CHECKS.filter((c) => !checks[c.key]).length;
    const stale = p.copyright && +p.copyright < new Date().getFullYear() - 2;

    return {
      url: bare, finalUrl, reachable: true, verified: true, rendered: true,
      ms, kb: Math.round(p.bytes / 1024), checks, gaps,
      info: { title: p.title, description: p.description, copyrightYear: p.copyright ? +p.copyright : null },
      stale,
      namesBusiness: expectName ? namesBusiness(expectName, p.title + ' ' + p.text) : null,
      reason: stale ? `© ${p.copyright}` : null,
    };
  } catch (e) {
    await ctx.close().catch(() => {}); if (own) await b.close().catch(() => {});
    return fail('render failed: ' + e.message, false);
  }
}


// Does this page actually belong to the business we think it does?
//
// Directory data hands us the wrong address more often than it hands us a bad
// one: an expired domain now resold, a listing on some aggregator's site, a
// competitor's page. The audit is perfectly accurate about whatever page it is
// given — it just has no idea the page is not theirs, and every finding then
// gets said out loud to an owner whose real site is fine.
const GENERIC = new Set([
  'the', 'and', 'inc', 'llc', 'ltd', 'co', 'company', 'corp', 'group',
  'center', 'centre', 'services', 'service', 'shop', 'store', 'studio',
  'san', 'diego', 'california', 'ca', 'usa', 'best', 'quality', 'professional',
]);

function namesBusiness(name, pageText) {
  const flat = String(pageText || '').toLowerCase().replace(/[^a-z0-9]/g, '');
  const words = String(name || '').toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter((w) => w.length >= 3 && !GENERIC.has(w));
  if (!words.length) return null;          // nothing distinctive to look for
  const hits = words.filter((w) => flat.includes(w)).length;
  return hits / words.length >= 0.6;
}

module.exports = { auditRendered, chromium, EXEC, namesBusiness };
